### ISSUE TITLE
save stage damage throws out of memory exception

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1050]
When saving stage damage functions for the freeport study, an out of memory exception is thrown when the software attempts to parse a Linq XML object to string. 

The exception is thrown here: https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/ec6b00ec3917a5f480ca165abb78828350889d5c/HEC.FDA.ViewModel/Storage/Connection.cs#L200 

The freeport study can be found here: `\\share.hec.usace.army.mil\USACE\Nugent\ForArden\Freeport Run 1-4-24`

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/9ad7b1ec-9392-40f7-af43-64dccc9f4045)

### Call Stack

` at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at System.Xml.Linq.XNode.ToString()
   at HEC.FDA.ViewModel.Storage.Connection.EscapeSingleQuotes(Object value) in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\Storage\Connection.cs:line 200
   at HEC.FDA.ViewModel.Storage.Connection.InsertIntoTableText(Object[] rowData, String tablename, String[] colnames) in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\Storage\Connection.cs:line 220
   at HEC.FDA.ViewModel.Storage.Connection.AddRowToTableWithPrimaryKey(Object[] rowData, String tablename, String[] colnames) in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\Storage\Connection.cs:line 191
   at HEC.FDA.ViewModel.Saving.SavingBase`1.SaveNewElementToTable(Object[] rowData, String[] TableColumnNames, Type[] TableColumnTypes) in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\Saving\SavingBase.cs:line 110
   at HEC.FDA.ViewModel.Saving.SavingBase`1.SaveNew(ChildElement element) in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\Saving\SavingBase.cs:line 96
   at HEC.FDA.ViewModel.Editors.BaseEditorVM.Save(ChildElement elementToSave) in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\Editors\BaseEditorVM.cs:line 123
   at HEC.FDA.ViewModel.AggregatedStageDamage.AggregatedStageDamageEditorVM.SaveCalculatedCurves() in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\AggregatedStageDamage\AggregatedStageDamageEditorVM.cs:line 118
   at HEC.FDA.ViewModel.AggregatedStageDamage.AggregatedStageDamageEditorVM.Save() in C:\Code\C#\HEC-FDA\HEC.FDA.ViewModel\AggregatedStageDamage\AggregatedStageDamageEditorVM.cs:line 151
   at HEC.FDA.View.Commands.SaveCommand.Execute(Object parameter) in C:\Code\C#\HEC-FDA\HEC.FDA.View\Commands\SaveCommand.cs:line 30
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by rnugent3** [comment]
Replicate by computing stage damage for freeport, and attempt to save.

**Comment by rnugent3** [comment]
Confirmed that this bug is isolated to Freeport, so something in the result is weird

**Comment by rnugent3** [comment]
It is not that there are too many stage-damage functions and the quantity of functions are overwhelming the memory in strings. I have just computed London Orleans with the original 90 or so impact areas and saved successfully

**Comment by rnugent3** [comment]
bin width issue is resolved
