### ISSUE TITLE
Scenario results exception 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#471]
I am unable to view Scenario results. I hit the following exception. 

Exception Message: 

Could not load file or assembly 'PlottingLibraryCore, Version=1.1.8203.26265, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Call Stack:

 at HEC.FDA.ViewModel.ImpactAreaScenario.Results.DamageWithUncertaintyVM..ctor(ImpactAreaScenarioResults iasResult, ScenarioResults scenarioResults)
   at HEC.FDA.ViewModel.ImpactAreaScenario.Results.SpecificIASResultVM.loadVMs(List`1 damCats, ScenarioResults scenarioResults, Int32 impactAreaID) in C:\Code\C#\FDA\HEC-FDA\ViewModel\ImpactAreaScenario\Results\SpecificIASResultVM.cs:line 129
   at HEC.FDA.ViewModel.ImpactAreaScenario.Results.SpecificIASResultVM..ctor(String iasName, Int32 impactAreaID, ScenarioResults scenarioResults, List`1 damCats) in C:\Code\C#\FDA\HEC-FDA\ViewModel\ImpactAreaScenario\Results\SpecificIASResultVM.cs:line 96
   at HEC.FDA.ViewModel.ImpactAreaScenario.IASElementSet.GetResults() in C:\Code\C#\FDA\HEC-FDA\ViewModel\ImpactAreaScenario\IASElementSet.cs:line 183
   at HEC.FDA.ViewModel.ImpactAreaScenario.IASElementSet.ViewResults(Object arg1, EventArgs arg2) in C:\Code\C#\FDA\HEC-FDA\ViewModel\ImpactAreaScenario\IASElementSet.cs:line 207
   at HEC.FDA.View.Utilities.ContextMenuConverter.<>c__DisplayClass0_0.<System.Windows.Data.IValueConverter.Convert>b__1(Object ob, RoutedEventArgs ev) in C:\Code\C#\FDA\HEC-FDA\View\Utilities\ContextMenuConverter.cs:line 146
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rnugent3** [comment]
main branch

**Comment by codymccoy** [comment]
If it can't find plotting library core, that sounds like a Brennan question. I am assigning him to this issue.

I am computing peres "Without Base Year" scenario and it is taking a long time. Has something changed? I feel like it is taking a lot longer than it used to.

**Comment by codymccoy** [comment]
@Brennan1994 Can you take a look at this platting library issue that Richard is experiencing.

**Comment by Brennan1994** [comment]
@rnugent3 , we can look at this today if you're coming in. I'm curious if you see that library in the distrubtion you're running. Its still in the one I downloaded.

**Comment by rnugent3** [comment]
I am not coming in today. Hopefully you can meet at 1:30 and we could look at it then?

**Comment by Brennan1994** [comment]
I believe we've closed this out.

**Comment by rnugent3** [comment]
that's right. I am able to view scenario results.
