### ISSUE TITLE
cannot import impact areas

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#473]
on the stage_damage_edited branch, I attempted to import impact areas, and hit the following exception. I notice a reference to LifeSimGIS below. I thought we had completely walked away from that dependency? 

Exception Message: 

Could not load file or assembly 'GDALAssist, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Call Stack: 

  at LifeSimGIS.ShapefileReader..ctor(String shapefile)
   at HEC.FDA.ViewModel.Saving.PersistenceManagers.ImpactAreaPersistenceManager.SaveImpactAreaTable(ImpactAreaElement element) in C:\Code\C#\FDA\HEC-FDA\ViewModel\Saving\PersistenceManagers\ImpactAreaPersistenceManager.cs:line 76
   at HEC.FDA.ViewModel.Saving.PersistenceManagers.ImpactAreaPersistenceManager.SaveNew(ChildElement element) in C:\Code\C#\FDA\HEC-FDA\ViewModel\Saving\PersistenceManagers\ImpactAreaPersistenceManager.cs:line 132
   at HEC.FDA.ViewModel.ImpactArea.ImpactAreaImporterVM.Save() in C:\Code\C#\FDA\HEC-FDA\ViewModel\ImpactArea\ImpactAreaImporterVM.cs:line 128
   at HEC.FDA.View.Commands.OkCommand.Execute(Object parameter) in C:\Code\C#\FDA\HEC-FDA\View\Commands\OkCommand.cs:line 35
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rnugent3** [comment]
The study data is bear creek mix

**Comment by rnugent3** [comment]
I had not rebuilt. I do not run into this problem on stage_damage_edited
