### ISSUE TITLE
Uncaught Exception in Create New Index Points 

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#609]
Because I forgot the test study data I was using did not have a shapefile for index points, so I went to close the dialog, but clicked OK accidently when meant to click Close. 

Image:
![image](https://user-images.githubusercontent.com/89167848/199509361-3aaf9247-1414-4049-b8f2-b214f27d581a.png)

Call Stack:
at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at HEC.FDA.ViewModel.Saving.PersistenceManagers.StudyFilesManager.CopyFilesWithSameName(String sourcePath, String newDirectoryName, Type childElementType) in /_/ViewModel/Saving/PersistenceManagers/StudyFilesManager.cs:line 63
   at HEC.FDA.ViewModel.IndexPoints.IndexPointsEditorVM.Save() in /_/ViewModel/IndexPoints/IndexPointsEditorVM.cs:line 110
   at HEC.FDA.View.Commands.OkCommand.Execute(Object parameter) in /_/View/Commands/OkCommand.cs:line 35
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rnugent3** [comment]
Looks like we need a tad bit of validation, here @codymccoy. @jbslaughter thanks for reporting this.

**Comment by codymccoy** [comment]
I added a property rule that looks at the number of index point rows in the table. The OK button will be disabled until there are at least one row in the table:
![image](https://user-images.githubusercontent.com/47757848/200383507-ab72ab1b-dc38-425a-987c-d6988b971b6c.png)

Please let me know if you want the wording changed. The message is in this class:
![image](https://user-images.githubusercontent.com/47757848/200383610-ca6f1e4d-d830-490c-8975-e32b5bd2c4fe.png)

This was completed on branch stage_damage_exception
