### ISSUE TITLE
Editing imported structure inventory (select shapefile allowed) - Click finish causes uncaught exception

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#800]
Uncaught exception - editing imported structure inventories.
Select shapefile allowed.
Update information and click finish and Uncaught Exception occured:

Call Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at HEC.FDA.ViewModel.Utilities.ChildElement.CloneElement() in C:\Code\C#\FDA\HEC-FDA\ViewModel\Utilities\ChildElement.cs:line 143
   at HEC.FDA.ViewModel.Editors.BaseEditorVM..ctor(ChildElement elem, EditorActionManager actionManager) in C:\Code\C#\FDA\HEC-FDA\ViewModel\Editors\BaseEditorVM.cs:line 72
   at HEC.FDA.ViewModel.Inventory.ImportStructuresFromShapefileVM..ctor(ChildElement elem, EditorActionManager actionManager) in C:\Code\C#\FDA\HEC-FDA\ViewModel\Inventory\ImportStructuresFromShapefileVM.cs:line 56
   at HEC.FDA.ViewModel.Inventory.InventoryElement.EditElement(Object sender, EventArgs e) in C:\Code\C#\FDA\HEC-FDA\ViewModel\Inventory\InventoryElement.cs:line 85
   at HEC.FDA.View.Utilities.ContextMenuConverter.<>c__DisplayClass0_0.<System.Windows.Data.IValueConverter.Convert>b__1(Object ob, RoutedEventArgs ev) in C:\Code\C#\FDA\HEC-FDA\View\Utilities\ContextMenuConverter.cs:line 146
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rnugent3** [comment]
Good catch. I don't think that select shapefile should be allowed.

**Comment by rnugent3** [comment]
Thanks @codymccoy
