### ISSUE TITLE
Alternative Results Uncaught Exception: Specified Visual is already a child of another Visual or the root of a CompositionTarget.

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#801]
build provided: 2023-02-24

Uncaught exception reviewing alternative results. 
Review: https://www.hec.usace.army.mil/confluence/display/FDATutorials/HEC-FDA+Workshop+4+Draft and follow the steps described in the workshop.
Exception occurred when selecting the AAEQ and Damage with Uncertainty option.

Message: Specified Visual is already a child of another Visual or the root of a CompositionTarget.
Call Stack:
 at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at SciChart.Charting.Visuals.ChartModifierSurface.vbe(UIElement ad)
   at SciChart.Core.Extensions.EnumerableExtensions.ForEachDo[T](IEnumerable`1 enumerable, Action`1 operation)
   at SciChart.Charting.Visuals.ChartModifierSurface.vaz(Object w, NotifyCollectionChangedEventArgs x)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at SciChart.Charting.ChartModifiers.VerticalSliceModifierBase.AttachRolloverMarker(FrameworkElement rolloverMarker)
   at SciChart.Charting.ChartModifiers.RolloverModifier.vpi(FrameworkElement gou, SeriesInfo gov)
   at SciChart.Charting.ChartModifiers.RolloverModifier.HandleMasterMouseEvent(Point mousePoint)
   at SciChart.Charting.ChartModifiers.InspectSeriesModifierBase.eeo(Point giq)
   at SciChart.Charting.ChartModifiers.InspectSeriesModifierBase.HandleMouseEvent(ModifierMouseArgs e)
   at SciChart.Charting.ChartModifiers.InspectSeriesModifierBase.OnModifierMouseMove(ModifierMouseArgs e)
   at SciChart.Charting.ChartModifiers.ModifierGroup.hvw(Action`2 gkh, ModifierEventArgsBase gki)
   at SciChart.Core.Utility.Mouse.MouseManager.hhq(ModifierMouseArgs bij, IReceiveMouseEvents bik, Boolean bil)
   at SciChart.Core.Extensions.EnumerableExtensions.ForEachDo[T](IEnumerable`1 enumerable, Action`1 operation)
   at SciChart.Core.Utility.Mouse.MouseManager.hhf(IReceiveMouseEvents bhh, ModifierMouseArgs bhi, Action`3 bhj)
   at SciChart.Core.Utility.Mouse.MouseManager.hhc(IPublishMouseEvents bha, IReceiveMouseEvents bhb, MouseEventArgs bhc, MouseButtons bhd, Action`3 bhe)
   at SciChart.Core.Utility.Mouse.MouseManager.the.nem(Object bjs, MouseEventArgs bjt)
   at drh.hei(Object blm, MouseEventArgs bln)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rnugent3** [comment]
@codymccoy please make this your first priority

**Comment by jbslaughter** [comment]
It seems like the exception occurs when I have a scenario and alternatives report open at the same time... and walk through the report options looking for answers to the workshop questions...

**Comment by rtle76** [comment]
![image](https://user-images.githubusercontent.com/67108837/221689104-c52f3ed2-3e4c-4c8f-857d-0db04525496a.png)

See image. I was finishing up with workshop 4 from prospect 209. I was navigating through the results from the alternative. I was clicking through the different dropdowns rather quickly and the uncaught exception popped up. I would close and it would pop up again, and again, and again

**Comment by codymccoy** [comment]
This is an issue that we tackled a long time ago and must have missed this one. The issue is that sci chart only allows one chart model per chart. When the tabs get popped out the chart model has to be handled special or else two get assigned to the chart and it throws the exception. Best strategy is to find out where those charts and chart models are located and how we handle other tabs with charts when they get popped out. I will try to take a look at some point this week.

**Comment by codymccoy** [comment]
Popping the tab out creates a new chart in a new window but tries to use the same chart model from the view model class. I think we have to just create a new copy of the chart model when the popping out happens. Something like that.

**Comment by codymccoy** [comment]
@rtle76 @jbslaughter Do you know if you were popping the tabs out into their own windows? I have not been able to reproduce this issue.

**Comment by codymccoy** [comment]
I was just able to reproduce this issue. Let me see if I can do it again.

**Comment by codymccoy** [comment]
I can't reproduce this again. Does anyone have a dependable way of reproducing this?

**Comment by codymccoy** [comment]
I'm giving up on this one for now. I am guessing these lines of code has something to do with this issue. 
![image](https://user-images.githubusercontent.com/47757848/221962736-8b2c8121-5e22-4826-8f8b-4d8a48542743.png)
![image](https://user-images.githubusercontent.com/47757848/221962762-e1c7b474-b33d-4de1-9870-2c9290d77ca9.png)

**Comment by jbslaughter** [comment]
Here's the study that I found the exception in: 
[Workshop4_Solution.zip](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/10854748/Workshop4_Solution.zip)

**Comment by codymccoy** [comment]
I tried the workshop study and still could not reproduce this issue. Based on the exception, the issue happens when the mouse goes over the plot. Maybe that will help someone else with trying to reproduce this issue.

**Comment by codymccoy** [comment]
If someone does reproduce this, try to copy the call stack text in its entirety and past it in here.
