### ISSUE TITLE
edit graphical frequency overflow 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#874]
I am not able to edit a graphical frequency function - I hit an overflow exception. 

![image](https://user-images.githubusercontent.com/25163165/233746380-c9b73e72-f351-43ae-af06-91a0a0e5eb31.png)

```
 at System.Convert.ToInt64(Double value)
   at Statistics.Histograms.Histogram.AddObservationToHistogram(Double observation, Int64 index) in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.Statistics\Histograms\Histogram.cs:line 385
   at HEC.FDA.Model.extensions.ContinuousDistributionExtensions.BootstrapToUncertainPairedData(ContinuousDistribution continuousDistribution, IProvideRandomNumbers randomProvider, Double[] ExceedanceProbabilities, Int32 realizations, Double histogramBinWidth) in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.Model\extensions\ContinuousDistributionExtensions.cs:line 42
   at HEC.FDA.ViewModel.FrequencyRelationships.AnalyticalFrequencyEditorVM.GetCoordinatesFunction() in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.ViewModel\FrequencyRelationships\AnalyticalFrequencyEditorVM.cs:line 391
   at HEC.FDA.ViewModel.FrequencyRelationships.AnalyticalFrequencyEditorVM.UpdateChartLineData() in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.ViewModel\FrequencyRelationships\AnalyticalFrequencyEditorVM.cs:line 318
   at HEC.FDA.View.FrequencyRelationships.AnalyticalFrequencyEditor.rad_standard_Checked(Object sender, RoutedEventArgs e) in C:\Code\C#\FDA\HEC-FDA\HEC.FDA.View\FrequencyRelationships\AnalyticalFrequencyEditor.xaml.cs:line 82
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.RadioButton.OnChecked(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Brennan1994** [comment]
There's something nasty happening here with saving and loading. You can create a new curve fine. It's only when you load existing data that it blows up. It tries to sample a LP3 with a record length of 1. Trouble is there shouldn't be an LP3 with sample length of 1 saved. Either it's getting saved inappropriately or loaded inappropriately. Testing.

**Comment by Brennan1994** [comment]
This UI is old and a confusing. Cody and I have talked about it many times. I think I'm going to move forward with a pretty substantial rewrite of it that will fix the saving issue here. I think it's important to do this now because I'm going to change the way we save this information to disk, which will break older studies, and it needs to be done before there are many existing studies out there. 

I'll do my best to ensure existing studies are foward migratable, it just won't be seamless.

**Comment by rnugent3** [comment]
Sounds good - thank you!!
